# Generated by Django 4.0a1 on 2021-10-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
    ]
