# Generated by Django 4.0a1 on 2021-10-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_remove_album_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_artist',
            new_name='artist',
        ),
    ]
